# Generated by Django 4.1.2 on 2022-12-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DenormalizedAdvertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advertisement", models.UUIDField(editable=False)),
                ("group", models.UUIDField(editable=False)),
                ("campaign", models.UUIDField(editable=False)),
                ("site", models.UUIDField(editable=False)),
                ("slot", models.UUIDField(editable=False)),
                ("tags", models.TextField()),
                ("data", models.TextField()),
            ],
        ),
    ]
